### ISSUE TITLE
Feature 1: User can access/view a (random) quote.

### ISSUE THREAD

**Issue by d-tak** [d-tak/thinking-thoughts#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can access/view a (random) quote.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Overall objective: In what is perhaps one of the most digitally connected eras known to human kind, people are often heard talking about feelings of isolation.  The purpose of this simple application is to provide a randomized, inspirational quote that will encourage users to use the text field to "soundboard" their thoughts - wins, losses, joys, frustrations, etc. - with the option to save and return to their entries - or simply "like" the quote without saving their thoughts.

Feature 1 objective: users will be able to read a quote.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="650" alt="Screen Shot 2022-08-01 at 4 50 04 PM" src="https://user-images.githubusercontent.com/99932512/182265694-c49bac0c-a512-4271-8269-a2f2875db6ce.png">
<img width="265" alt="Screen Shot 2022-08-01 at 4 50 27 PM" src="https://user-images.githubusercontent.com/99932512/182265731-485ef81a-f67d-4dcf-b2d1-9d2555a24ddf.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Create the necessary HTML structure.
- [x] Create basic CSS structure
- [x] Make an API call (request)
       // https://api.goprogram.ai/inspiration
- [x] Get the response.
       // var response = await fetch(api_url);
- [x] Parse response to JSON format
- [x] Retrieve data from JSON
- [x] Accessing the div and modify/add elements
- [x] Create a new element and append

  - [x] Make sure that click targets are either `<a>` or `<button>` elements.
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
  - [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
  - [x] Test all functionality again in a private browsing session.
  - [x] Fix all errors.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by d-tak** [comment]
<img width="1180" alt="Screen Shot 2022-08-02 at 12 58 35 PM" src="https://user-images.githubusercontent.com/99932512/182463715-4b21c480-2598-4851-964b-ce8b12615b29.png">
