### ISSUE TITLE
Feature 2: User can like the daily quote

### ISSUE THREAD

**Issue by d-tak** [d-tak/thinking-thoughts#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can like the quote

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to press the like button for the quote, which will then save the quote in the "Liked Thoughts" tab.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="679" alt="Screen Shot 2022-08-01 at 5 42 38 PM" src="https://user-images.githubusercontent.com/99932512/182268121-2e1f09b7-1f31-4654-b382-7e24aa10c12f.png">
<img width="248" alt="Screen Shot 2022-08-01 at 5 46 12 PM" src="https://user-images.githubusercontent.com/99932512/182268269-778eb4bf-0501-4a6c-b6de-a7135c365058.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Update "Today's Thoughts" to include a "LIKE" button for each rendered entry.
- [x] Listen for clicks on the quote element --> li
- [x] Save "liked quote" 
- [x] Define a function that takes a single quote and returns a DOM tree.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by d-tak** [comment]
<img width="1160" alt="Screen Shot 2022-08-02 at 3 47 19 PM" src="https://user-images.githubusercontent.com/99932512/182673327-79f55add-ab2a-489b-9671-60ec1c03794c.png">
