### ISSUE TITLE
Feature 3: User can view liked quotes

### ISSUE THREAD

**Issue by d-tak** [d-tak/thinking-thoughts#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view liked quotes

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to click on the "Liked Thoughts" button to access liked quotes.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="679" alt="Screen Shot 2022-08-01 at 5 43 07 PM" src="https://user-images.githubusercontent.com/99932512/182268616-0bb3492e-daef-4a21-9a78-b396e6f8c9cd.png">
<img width="677" alt="Screen Shot 2022-08-01 at 5 43 33 PM" src="https://user-images.githubusercontent.com/99932512/182268627-80a65a78-ce1c-49a0-893e-b549c4b6fc3a.png">
<img width="248" alt="Screen Shot 2022-08-01 at 5 46 12 PM" src="https://user-images.githubusercontent.com/99932512/182268643-ad0cc4b5-bcc9-4c82-b1d4-0d6ab7fa7125.png">
<img width="248" alt="Screen Shot 2022-08-01 at 5 48 57 PM" src="https://user-images.githubusercontent.com/99932512/182268650-eb16f83b-a45f-455d-be8d-7bba3dbbe400.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Add an empty unordered list to the `div[data-view="entries"]` element in the HTML.
- [x] Add some dummy quotes to the unordered list in the HTML and style them to match the wireframe.
- [x] Check that the entries list looks good on both mobile and desktop screens.
- [x] Create a DOM tree for each entry in the data model and append it to the page when the `'DOMContentLoaded'` event is fired.
- [x] Remove the example HTML entries once the user's entries are successfully being appended to the DOM on page load.
- [x] Add a navigation item for "Liked Thoughts".
- [x] Add an anchor to the "liked" view that shows the "Liked Thoughts".
- [x] Ensure that refreshing the pages shows the same view as before refreshing.
- [x] Pressing on logo "Thinking Thoughts" will return to landing page.
- [x] Test the app some more in a private browsing tab.
- [x] Fix all errors.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
