### ISSUE TITLE
Feature 4: User can enter a text entry (journal) about the liked quote.

### ISSUE THREAD

**Issue by d-tak** [d-tak/thinking-thoughts#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can enter a text entry (journal) about the liked quote.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to use the text box to make a journal entry - save, or simply discard as a soundboard mechanism.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
<img width="679" alt="Screen Shot 2022-08-01 at 10 03 41 PM" src="https://user-images.githubusercontent.com/99932512/182295893-5f23972b-2cc3-4322-b930-d533188d9e7d.png">
<img width="246" alt="Screen Shot 2022-08-01 at 10 04 11 PM" src="https://user-images.githubusercontent.com/99932512/182295906-50bd61ea-79d1-4ec5-aac2-7a95337dc3d4.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Add a text input field to the existing view that enables users to enter a journal entry.
- [x] Add a Think button below the text input
- [x] Listen for submit events on the entry and
  - [x] Put the form's input values into the Data Model.
  - [x] Add the `nextEntryId` to the object.
  - [x] Increment the `nextEntryId` on the data model.
  - [x] Match the ID of the entries with the quote cards.
- [x] Verify that new entries are saved to local storage along with the rest of the data model on page reload.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
