### ISSUE TITLE
Feature 5: User can view entry for the liked quote.

### ISSUE THREAD

**Issue by d-tak** [d-tak/thinking-thoughts#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view saved journal entries.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Should users choose to save a text entry, users will be able to access their journal by clicking on the "Journal" button.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="676" alt="Screen Shot 2022-08-01 at 10 06 44 PM" src="https://user-images.githubusercontent.com/99932512/182296128-3387678b-2046-46fb-be34-5101ea13e8c9.png">
<img width="243" alt="Screen Shot 2022-08-01 at 10 06 27 PM" src="https://user-images.githubusercontent.com/99932512/182296136-fcc06fe7-9cbf-45d4-9336-fb93dc5fe053.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] ...
- [x] Add an empty unordered list to the `div[data-view="entries"]` element in the HTML.
- [x] Add a navigation item for "Journal".
- [x] Add an anchor to the entries view that shows the "Journal".
- [x] Add some dummy quotes to the unordered list in the HTML and style them to match the wireframe.
- [x] Check that the entries list looks good on both mobile and desktop screens.
- [x] Create a DOM tree for each entry in the data model
- [x] Remove the example HTML entries once the user's entries are successfully being appended to the DOM on page load.
- [x] Ensure that refreshing the pages shows the same view as before refreshing.
- [x] Test the app some more in a private browsing tab.
- [x] Fix all errors.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
